[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install --network-timeout 100000"]

[phases.build]
cmds = ["CI=false DISABLE_ESLINT_PLUGIN=true yarn build"]

[start]
cmd = "npx serve -s build -l 3000"
