[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install fastapi uvicorn motor pymongo python-dotenv python-multipart pydantic fpdf2 openpyxl python-jose passlib bcrypt httpx"]

[start]
cmd = "python -m uvicorn server:app --host 0.0.0.0 --port 8001"
